# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" , "master"]


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: git fetch --prune --unshallow
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: get ipaddress
      run: ifconfig
    - name: built docker
      run: |
        docker build -t application .
    - name: run docker
      run: |
        docker run application
#    - name: run server
#      run: python3 main.py
#    - name : Deploy to Heroku
#      env:
#        HEROKU_API_TOKEN: ${{secrets.HEROKU_API_TOCKEN}}
#        HEROKU_APP_NAME: ${{secrets.HEROKU_APP_NAME}}
#        run: |
#          git remote add heroku https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git
#          git push heroku HEAD:master -f
